### ISSUE TITLE
福岡Groonga1

### ISSUE THREAD

**Issue by linyows** [groonga/meetup#1]
http://groonga.doorkeeper.jp/events/19433

**Comment by linyows** [comment]
会場で準備できること
- 椅子・机など ３０人分（ただ、追加注文しているので当日もっとあるかもしれない。広さ的にはもっと人数入れます）
- Wi-Fi
- プロジェクター（コネクターは調べます）
- （追記）ホワイトボード

**Comment by linyows** [comment]
@kou イベント内容みる限り懇親会はなさそうなんですがあってますかねー

**Comment by kou** [comment]
懇親したいです！
福岡を満喫したいです！

**Comment by linyows** [comment]
お、了解です〜

> 福岡を満喫したいです！

会場でやるよりどっかお店おさえたほうがよさそうですね。

**Comment by linyows** [comment]
リクエストありますか？幹事は @udzura さんがやってくれるとのこと...

**Comment by kou** [comment]
> リクエストありますか？幹事は @udzura さんがやってくれるとのこと...

うぉー！ありがとうございます！

福岡の人が福岡に来た人に食べさせたいもの、がいいです！（嫌いなものはありません。）

**Comment by kou** [comment]
> - 椅子・机など ３０人分（ただ、追加注文しているので当日もっとあるかもしれない。広さ的にはもっと人数入れます）

人数は10人いかないくらいのこじんまりしたものになるんじゃないかと思っています。（福岡でのGroonga普及率がよくわかっていない。）

> - Wi-Fi

イベントページにWi-Fi使えると書きました！

もし、ホワイトボード的なものがあったら貸してもらえると嬉しいです。（絵を書きながら動作や仕組みを説明したい。）
無理そうなら、紙とペンを持っていきます！

**Comment by linyows** [comment]
ホワイトボードは可動式のが２つほどあるので大丈夫です！

**Comment by kou** [comment]
すごい！
とても助かります！

**Comment by udzura** [comment]
> 人数は10人いかないくらいのこじんまりしたものになるんじゃないかと

なるほど...
懇親会は、その場で手を上げていただいてその場で取る感じで大丈夫そうですね。

**Comment by linyows** [comment]
あらかじめお店予約とれたほうが、美味しいところいけそう

**Comment by udzura** [comment]
@kou 

http://groonga.doorkeeper.jp/ に、懇親会用のイベントを作成していただけるとありがたいです〜（純粋に人数把握のためです）
とはいえ5 ~ 6名かな？

**Comment by kou** [comment]
作成しました！ http://groonga.doorkeeper.jp/events/19728

**Comment by udzura** [comment]
@kou 懇親会こちらで... http://r.gnavi.co.jp/f042104/
みつせ鶏！　水炊き！　な感じです。

**Comment by kou** [comment]
すごい！カンペキです！
イベントページに書きました！

（関係ないですけど、明日の16時くらいか明後日の11時くらいに、元気一杯か大名の一風堂本店にチャレンジしたいなぁと思っています。）

**Comment by kou** [comment]
会場提供、懇親会予約ありがとうございました！
（ホワイトボードも用意してもらえてとても助かりました。）
おかげで充実した時間になりました！感謝しています！

また、福岡に来ることがあったらお世話になるかもしれませんが、そのときもどうぞよろしくお願いします！

**Comment by linyows** [comment]
@kou イベントありがとうございました！いえいえ、お手伝いできて良かったです！はい、また声かけてください〜。ステッカーも沢山いただきありがとうございます :octocat:
