### ISSUE TITLE
Groonga Meatup 2017：発表応募場所

### ISSUE THREAD

**Issue by myokoym** [groonga/meetup#17]
[Groonga Meatup 2017](https://groonga.doorkeeper.jp/events/55616)で発表してくださる方を募集します。テーマは、「もっとGroongaを好きになる話」です。

「Groonga Meatup」はGroongaがメインのイベントなので、参加者はGroongaを知っている／使っている人が多いです。そのため、Groongaを知っている／使っている人同士で情報共有することができます。その情報共有を、休憩時間や懇親会での会話にとどまらず、発表としてやってみてはどうでしょうか。Groongaを知らない人に遠慮することなく、普段はあまりできないような、Groongaを知っている／使っている人向けの話をしてもらえたらと思っています。

例:

* 深い話
* 工夫したことの自慢
* 別分野との組み合わせ
  * JMAT（自然言語処理、トークナイザー）、Fluentd、Rails
* ベンチマーク比較
* 悩んでいることの相談

もちろん、Groongaに限らず、MroongaやPGroonga、Rroongaなど、Groonga関連プロダクトの話題でも大丈夫です。

発表してくれる方は↓の内容をコメントに書いてください。
- 発表時間
  - ~~5分、10分、15分 、20分、30分から選んでください。←以外の時間にしたい方はコメントでその旨を相談してください。~~  （発表枠が埋まったので締め切りました！たくさんのご応募ありがとうございました）
- 発表タイトル
- 発表者の表記
  -  例：`@groonga`（Twitterのアカウント名）、山田 太郎（名前）、ぐるんが（ニックネーム）
  - デフォルトはコメントしたGitHubアカウント名になります。

参考: Groonga Meatup 2015：発表応募場所 #12

**Comment by myokoym** [comment]
例:

* 発表時間：10分
* 発表タイトル：Rroongaで小さなWebサイトに全文検索を導入した話（仮）
* 発表者の表記：@myokoym（Twitterのアカウント名）

**Comment by yoku0825** [comment]
こんにちはこんにちは。

- 発表時間: 15分
- 発表タイトル: Dockerイメージで誰でも気軽にMroonga体験
- 発表者の表記: yoku0825

よろしくお願いします :D

**Comment by kawano-gmom** [comment]
ここに書けばいいんですかね

- 発表時間:15分
- 発表タイトル: あれをこうしたら検索が速くなったよ(仮称)
- 発表者の表記: tkskwn

よろしくお願いします :-)

**Comment by myokoym** [comment]
@yoku0825 @kawano-gmom ありがとうございます！！イベントページに追記しました。

https://groonga.doorkeeper.jp/events/55616#time-table

時間や内容の変更などがあればお気軽にご連絡ください。楽しみにしています！

**Comment by piroor** [comment]
参加応募の期限を設けるのを失念していました。とりあえずの目安という事で、2月1日いっぱい（2月2日0時0分〆切）としたいと思います。発表をご検討いただいている方はお早めにエントリーいただけますと幸いです！

**Comment by atsuoishimoto** [comment]
よろしくお願いします。

発表時間：15分
発表タイトル：DjangoでPGroonga
発表者の表記：@atsuoishimoto

なるべく、遅めの時間に割り当てていただけると助かります

**Comment by myokoym** [comment]
@atsuoishimoto ご応募ありがとうございます！

20:35-20:50の枠でイベントページに追記しました。
https://groonga.doorkeeper.jp/events/55616#time-table

楽しみにしています！

**Comment by myokoym** [comment]
みなさん、ご応募ありがとうございます！
おかげさまで残り枠15分というところまで来ました。

**今後ご応募される方へ：**
残り枠が15分になったので、それを超える枠（20分、30分）については締め切りました。 
発表時間は 5分、10分、15分 から選んでください。

**Comment by muratapo** [comment]
がんばります。
発表時間: 15分
発表タイトル: Mroonga/Groonga適材適所(仮)
発表者の表記: むらたぽ
よろしくお願いします 。

**Comment by myokoym** [comment]
@muratapo ご応募ありがとうございます！

イベントページに追記しました。
https://groonga.doorkeeper.jp/events/55616#time-table

楽しみにしています！

**Comment by myokoym** [comment]
発表枠が無事に埋まったので、ここまでで締め切りとさせていただきます。
たくさんのご応募ありがとうございました！

不明点などがあればお気軽にコメントしてくださいませ。
