### ISSUE TITLE
Groonga Meatup 2017：イベント手伝い応募場所

### ISSUE THREAD

**Issue by myokoym** [groonga/meetup#18]
[Groonga Meatup 2017](https://groonga.doorkeeper.jp/events/55616)の開催を手伝ってくれる人を募集します！

手伝って欲しい内容：
- イベントレポート（前回はイベントレポートをgihyo.jpに載せてもらいました。これはgihyo.jpから原稿料が出ました。実際のレポート：[いい肉の日に開催，Groonga Meatup 2015レポート ～今年は新たにPGroongaが仲間に：レポート｜gihyo.jp … 技術評論社](http://gihyo.jp/news/report/2015/12/0801)（1,2名いるとよさそう。）
- Twitterでのイベント実況およびTogetterへのまとめ（1,2名いるとよさそう。）
- 当日の受付および会場係（~~3,4~~1,2名いるとよさそう。）
- 懇親会スタッフ（名札のシールの確認。1,2名いるとよさそう。）
- 動画配信（例年UstreamやYoutubeで配信していました。）（1名いるとよさそう。）

締め切り：2017年1月26日（木）23:59まで

顔合わせ日程：2017年1月27日（金） 19:30-21:00 場所: [株式会社クリアコード](https://www.clear-code.com/about/)

**Comment by ManabuSeki** [comment]
@kou 受付、会場係でお手伝いさせてください　😄

**Comment by kou** [comment]
@ManabuSeki ありがとうございます！

@myokoym @kenhys @piroor 段取りの連絡、お願いします！

**Comment by myokoym** [comment]
@ManabuSeki お申し出ありがとうございます！助かります。

今後の進め方ですが、締め切り後（平日の夜あたり）に手伝ってくれる人の顔合わせをして、具体的な役割分担などをする予定です。なので、もうしばらくお待ちくださいませ。
1/23（月）〜1/27（金）の間でご都合の良い日/悪い日があれば事前に教えていただけると助かります。

**Comment by ManabuSeki** [comment]
@myokoym

できれば26,27日(木、金)あたりだと助かります
顔合わせ場所によってはちょっと遅れるかもしれません

**Comment by myokoym** [comment]
@ManabuSeki ありがとうございます！了解です。日程が決まり次第、ここでご連絡します。

**Comment by myokoym** [comment]
@ManabuSeki ご連絡が遅くなってすみません。協力者の顔合わせを27日（今週金曜）の19:30から[株式会社クリアコード](https://www.clear-code.com/about/)で実施しようと考えているのですが、ご都合はいかがでしょうか？

今のところの参加者は↓です。協力者はまだ募集中なので増えるかもしれません。

* 運営チーム
  * @kenhys 
  * @piroor 
  * @myokoym
* 協力者
  * @ManabuSeki さん
  * @murasakiToshiya さん

進め方ですが、以下の流れを予定しています。

* 簡単な自己紹介
* 当日の進め方の確認
  * 机・椅子の並び替え
      * 椅子だけ並べる
          * 机ありだと70人も座れない
          * ○roongaで分ける？→わけなくて良いのでは
      * 机はスクリーンの左側に寄せる
      * 現状復帰用に写真を撮っておく
  * プロジェクタは天井にある
  * Macのコネクタがあったほうが安心かも
  * 登録者確認
      * ~~バー~~QRコードを読み取る
  * 名札の書き方（シールの有無、アイコン印刷の有無）を決める
      * 白紙を渡して手書き＋シール
      * アイコンを載せたい人は各自でプリントしてもらう
      * アイコン印刷はプルリク次第で
  * 懇親会の会費徴収
      * 受付で支払い→シール渡す
      * 減った分が参加者数→お店に連絡できる
  * エレベーターホールに人がいたほうがいいかも？
  * 会場説明（トイレとか）
      * 最初の5分で司会がやる
      * 写真に写りたくない人はアピールしてください
      * Twitterのハッシュタグは #groonga です
  * SSID
      * 開始前のスクリーンに出しておく
* ノベルティ
  * ステッカー
* 役割の説明・分担
  * 司会（1名）
      * @piroor 
  * 当日の受付および会場係（2〜3名）
      * @ManabuSeki さん
      * @murasakiToshiya さん
      * 何かあれば @myokoym or @kenhys に声を掛けてもらう
  * ~~懇親会係（会場で名札シールの確認。1〜2名）~~ 常に名札をつけてもらうので不要
  * イベントレポート（1〜2名）
      * @kenhys 
      * 写真は大場さん？
          * 各発表者で（うまくなくてもいいので）1まいずつくらいあればよい
  * Twitterでのイベント実況およびTogetterへのまとめ（1〜2名）
      * @myokoym
* その他の相談事項
  * 懇親会メニュー https://r.gnavi.co.jp/plan/g863231/plan-reserve/plan/plan_list/?date=20170209&coursetime=2130&num=40&select_price_from=&select_price_to=4000&seat_only=on&sort=3#js-search-bar
      * 《2980円コース》カルパッチョや揚げ物盛合わせなど2次会にオススメ　全8品2H飲み放題付2980円
      * 当日の変更が難しいコースなら再検討
* （有志で懇親会）（候補）
  * [天王寺 はち八 - 大塚/たこ焼き](https://tabelog.com/tokyo/A1323/A132302/13132934/)
  * [上海チキン 大塚 小閣樓 - 大塚駅前/担々麺](https://tabelog.com/tokyo/A1323/A132302/13005631/) （LO22:00）
  * [蕎・馳走 岩舟 （きょう ちそう いわふね） - 大塚/そば](https://tabelog.com/tokyo/A1323/A132302/13017041/) （LO21:30）
  * [ととや 魚丸 大塚店 （ととや うおまる） - 大塚/居酒屋](https://tabelog.com/tokyo/A1323/A132302/13031327/)

**Comment by ManabuSeki** [comment]
@myokoym 
連絡遅くなりました。

問題ないです　参加します

あと、ウチの会社の人間でスタッフ手伝えるの見つけたので参加してもよいでしょうか？

Github: @murasakiToshiya

よろしくお願いします

**Comment by myokoym** [comment]
@ManabuSeki 

> 問題ないです　参加します

ありがとうございます！よろしくお願いします。

> あと、ウチの会社の人間でスタッフ手伝えるの見つけたので参加してもよいでしょうか？
> 
> Github: @murasakiToshiya

はい、ぜひお願いします！とても助かります。

では当日お待ちしております。
疑問点などがあれば、思いついたタイミングでいつでも聞いてもらって大丈夫です。

**Comment by murasakiToshiya** [comment]
@myokoym 

@ManabuSeki からお誘いを頂きました。
宜しくお願いします

**Comment by myokoym** [comment]
@murasakiToshiya ご連絡ありがとうございます！こちらこそよろしくお願いします。

**Comment by myokoym** [comment]
今日の進め方を更新しました。
https://github.com/groonga/meetup/issues/18#issuecomment-274713349

**Comment by kenhys** [comment]
当日の写真撮影は高橋さんに快諾していただけました。
https://twitter.com/k_taka

**Comment by myokoym** [comment]
懇親会費ですが、3500円で確定します。（半端ですみません…）
おつりはこちらで用意します。

**Comment by myokoym** [comment]
会場に向かっています。18:10頃着きそうです。
