### ISSUE TITLE
Groonga "Tokenizer" Talks

### ISSUE THREAD

**Issue by kou** [groonga/meetup#2]
- [x] イベントページ作成
- [x] 話者のスケジュール調整
- [x] イベント開催日確定
- [x] イベント会場確保
- [x] イベント告知
- [x] イベント開催

**Comment by kou** [comment]
http://groonga.doorkeeper.jp/events/20546

**Comment by kou** [comment]
ジャストシステムさんも話してくれることになりました！

**Comment by kou** [comment]
ジャストシステムさんは仮で入れていた3/13（金）で都合がよいということなので、 @naoa さんもその日で大丈夫そうなら3/13（金）19:00-（19:30-の方がいい？）で確定にします。どうでしょうか？

**Comment by naoa** [comment]
おお！私は大丈夫です！１９：００、１９：３０はどちらでも大丈夫です！ご飯食べる人のことを考えると１９：３０の方がありなのかもしれませんね

**Comment by kou** [comment]
では、3/13（金）19:30開始で確定します！19:00開場にしましょう。

**Comment by naoa** [comment]
了解です！色々ありがとうございます！

**Comment by kou** [comment]
@yoku0825 日程が3/13（金）19:00開場、19:30開始で確定したので会場を決めたいと思っています。前に提案してもらったところってまだ大丈夫ですか？あと、もし、参加希望者が殺到（！？）したら別のところに移るのはアリですか！？（殺到するかわかりませんが。。。）

ConoHaの人にも相談しようかなぁと思っていたんですけど、どう思いますか？（ConoHaの人にとってもうれしそうなイベントなら一緒にやるのはアリだと思うんですけど、集客力がどれだけあるイベントなのかわからないので、正直よくわからない。。。）

**Comment by yoku0825** [comment]
@kou 12席, 14席, 14席, 30席の4部屋と、8席の部屋が4～5部屋空いていました。当日キャンセルは(できればしてほしくはないですけど)OKです :) ConoHaの人、ぐるんべの時のようにチラシだけでもどうよ(もちろんセッションしてくれてもいいよ)って聞いてみましょうか？

**Comment by kou** [comment]
では、ConoHaの人にうっすら聞いてもらえますか！？ConoHaの人が興味を持ってくれて会場も提供しますよ！くらい言ってくれるならそこを使って（ConoHaの宣伝になりそう）、そこまでじゃなかったら30席の部屋でお願いしたいです！

**Comment by kou** [comment]
あ、キャンセルするとしても、当日キャンセルはしません！するとしても1,2週間くらい前です。直近1,2週間で殺到しても会場を動かして枠を増やす、とかはしません！

**Comment by yoku0825** [comment]
@kou 

> ConoHaの人が興味を持ってくれて会場も提供しますよ！くらい言ってくれるならそこを使って

や、彼らも手を伸ばせる範囲は俺とそうそう変わらないと思うので、今から30人以上入れる(外部も含めて)場所を確保するのは難しいんじゃないかと思います！ そこはそれとしてチラシ出展くらいは聞いておきます :)

3/13(金) 19:00～ 30人部屋は確保しました。

**Comment by yoku0825** [comment]
@kou おまけですが、他のイベントとカブらなければUst用の機材はGroonga "How-to"の時のと同じのが借りられると思います。

**Comment by kou** [comment]
会場のこと、もろもろわかりました！確保ありがとうございます！
https://manage.doorkeeper.jp/groups/groonga/events/20546/edit に会場情報を書いてくれるとうれしいいです！

**Comment by kou** [comment]
Ustわっほい！是非お願いします！

**Comment by yoku0825** [comment]
とりあえず更新しました。

**Comment by kou** [comment]
ありがとうございます！

**Comment by kou** [comment]
@naoa @yoku0825 すみません！
3/20（金）19:00からに変更するのは大丈夫でしょうか！？もう1人の発表者のジャストシステムさんが20の方がよさそうということでして。。。無理そうならそのまま13でも大丈夫です！

い、いかがでしょうか。。。！？

**Comment by naoa** [comment]
私は平気ですよ〜

**Comment by yoku0825** [comment]
@kou 3/20 18:30～ 22人部屋なら確保できますー

**Comment by yoku0825** [comment]
仮押さえなう。

**Comment by kou** [comment]
ありがとうございます！
では、3/20でお願いします！

**Comment by kou** [comment]
@naoa タイトルと概要が決まったら教えてもらえるとうれしいです！

近日中に告知しようと思っています！

**Comment by kou** [comment]
TwitterとFacebookとgroonga.orgで告知しました！

**Comment by naoa** [comment]
近日中のスパンがめっちゃみじかい！（数時間）

すいません、ちょっと今忙しくて手を出せてませんが、決まったらお伝えします！

**Comment by kou** [comment]
てへ！

よろしくおねがいしますー

**Comment by kou** [comment]
なんと22人集まっちゃいました。（今23人。）

**Comment by naoa** [comment]
Greate！
さすがジャストシステムさんですね！
言語処理界隈の人らに少し刺さったのかな

ちゃんと資料準備しないと。

事例紹介とかよりできるだけ具体的なトピックのほうがよかったりするのかも？

**Comment by kou** [comment]
> 事例紹介とかよりできるだけ具体的なトピックのほうがよかったりするのかも？

そうですね。技術的な話優先で大丈夫です！
こういうところで使っていますよーというより、
こういう技術的な背景があるのでこういうユースケースで効いています、ほらね、
みたいな方があうと思います。

**Comment by naoa** [comment]
了解です！

なんと、すでにキャンセル待ちになっちゃっているんですね

**Comment by yoku0825** [comment]
@kou 先生、いま気付いたんですが、22人部屋なので22人入れませんよ…？ （関係者全部含めて22脚しか椅子が入らないはず

**Comment by kou** [comment]
そうじゃないかなぁとは思っていたんですよね！

**Comment by yoku0825** [comment]
とりあえず隣の部屋に14名の部屋を講師控え室として確保しました。
椅子詰めて入れば22名の方にすし詰め、入らなかったら(関係者は)控え室でUstream視聴です！

**Comment by kou** [comment]
すごい！
ありがとうございます！

**Comment by kou** [comment]
@yoku0825 そういえば！なんですが！会場にホワイトボードってあります？質問に答えるときに絵を描いて説明した方がわかりやすいことがあるんじゃないかと思っていて、そのときにホワイトボードがあると便利だろうと思っています！

**Comment by yoku0825** [comment]
@kou 確保しましたー

**Comment by kou** [comment]
ありがとうございます！とてもとても助かります！！！

**Comment by yoku0825** [comment]
@kou できれば19:30の入館は遠慮したいところなんですが、ダメですかね…？ （結構面倒で、いつもの規模ならさっくり承認も降りるんですが今回はどうだろう。。

**Comment by yoku0825** [comment]
@kou あ、いや、何でもないです。ゲストカードの枚数を確定させるので、関係者サイド(Doorkeeperに登録していない人)の人数を教えてください！

**Comment by kou** [comment]
今のところ次の9人です。月曜日、改めて確認して確定させます！
- @naoa
- 内田さん（ジャストシステムの方）
- @yoku0825
- 須藤
- 横山さん
- 林さん
- 森さん
- ジャストシステムの方2人

**Comment by kou** [comment]
すっかり忘れていました！9人確定で大丈夫です！

**Comment by yoku0825** [comment]
@kou 22名 + 9名 - 1名(わたしセキュリティーカードいらない)= 30名でセキュリティーカード申請しました。

**Comment by kou** [comment]
Ustream配信のURLはどうしましょうか。
私は @yoku0825 さんのアカウントで配信でもいいんじゃないかと思っています。

**Comment by yoku0825** [comment]
@ktou チャンネル作りました http://www.ustream.tv/channel/groonga-tokenizer-talks
Doorkeeperのページも更新済みです。

**Comment by kou** [comment]
ありがとうございます！！！

**Comment by kou** [comment]
明日ですが、何時に会場入りするのがよさそうでしょうか？会場設営とかお手伝いします。
18:00とか18:30くらいでしょうか！？

（メモ：Groongaステッカーを忘れないこと。）

**Comment by yoku0825** [comment]
@kou 会議室が18:30からなので、18:30(に1Fにつくくらい)でお願いします！
関係者みなさん一緒だと喜びますが、別々なら別々でも問題ないです :)

**Comment by kou** [comment]
わかりました！
18:30に行きます！（何人行くかは確認してから連絡します。）

18:30に行かない人は19:00-19:30の間に普通の参加者と同じフローで入ってもらいます。

**Comment by kou** [comment]
私と森さんの2人だけ18:30に行きます！
他の人たちは参加者と同じフローで入ります！

よろしくお願いします！

**Comment by kou** [comment]
@naoa もし、少し余裕を持ってこれそうなら、イベント開始前にプロジェクターへの接続チェックとかして欲しいです！

**Comment by naoa** [comment]
すいません！バス間違えました！
迷子にならなければたぶん19時までにはいけそうです！

**Comment by kou** [comment]
参加者として
19時入場でお願いします！

**Comment by kou** [comment]
@yoku0825 会場提供ありがとうございました！助かりました！Mroongaのことで話したいことがあったんですが、それはまたの機会に！

@naoa 発表ありがとうございました！オーバーラップの回避は取り込んでもいい気がしたので、森さんにも聞いてみます。

ということで、無事にイベントは終わったのでこれはクローズします。ありがとうございました！

**Comment by yoku0825** [comment]
:+1:
