### ISSUE TITLE
Groongaソースコード読書会（仮）

### ISSUE THREAD

**Issue by kou** [groonga/meetup#4]
https://twitter.com/noranuk0/status/579828683512287232

> そういえば、先週末のgroonga talknizer talk でのgroonga内部のデータ構造の話を聞いて、groongaソースコード読書会的なものがあったらちょっと行ってみたいなーと思いました。

を実現できないか、というイベント。

TODOリスト:
- [x] 内容の検討
- [x] イベントページ作成
- [x] イベント開催日調整
- [x] イベント会場確保
- [x] イベント告知
- [x] イベント開催

**Comment by kou** [comment]
@noranuk0 さんを https://groonga.doorkeeper.jp/ の管理者に追加したので、イベントページは作成できるようになっているはずです！

**Comment by noranuk0** [comment]
権限追加ありがとうございます。
こういったイベントの企画設営のお仕事って初めてなので、至らない点もあるかと思いますが
出来るところから順にやっていきたいと思います。よろしくお願いします。

**Comment by kou** [comment]
http://groonga.org/ja/blog/2015/03/26/groonga-source-code-read-call-for-contributors.html に会場提供などで協力してもらいないかというアナウンスを出しておきました！

協力してくれる人が現れるといいなぁ。

**Comment by kou** [comment]
> こういったイベントの企画設営のお仕事って初めてなので、至らない点もあるかと思いますが
> 出来るところから順にやっていきたいと思います。よろしくお願いします。

私もソースコードを読むという内容のやつは初めてです！
なので、さぐりさぐり、無理のない範囲で進めていきましょう！

わからないところはここで相談すればなんとかなると思います。

よろしくお願いします！

**Comment by shogondo** [comment]
弊社のオフィス（外苑前）をご提供できます！
https://goo.gl/maps/FJywI
収容人数は最大30人（机を片付けて椅子のみにした場合）。
プロジェクター利用可能です。

僕もGroongaに以前から興味を持っていて、ソースコード読書会が開催されるなら是非参加したいと思っています！

**Comment by kou** [comment]
おぉ！ありがとうございます！

@noranuk0 さん、どう思いますか！？

**Comment by noranuk0** [comment]
とても良いと思います。

ある程度の人数が入る場所のあて、こちらでは見つけるのはちょっと厳しいので、非常にありがたいです。

**Comment by kou** [comment]
では、 @shoutakenaka さんが提供してくれる会場を使わせてもらいましょう！よろしくお願いします！

（@shoutakenaka さんもこのリポジトリーへの書き込み権限を設定しました。）

とすると次は↓を詰めていけばよさそうな気がします。
- 開催時期
- 内容（今日は転置索引の○○を読む、とかテーマを絞ったほうがよさそう？）

**Comment by noranuk0** [comment]
後、内容なのですが、

例えば、ありきたりですが
・コア機能のなにかの関連ソースを読んでみる。
・機能拡張のやり方(トークナイザの追加の話とか）の話。
・開発環境の話（開発者の方は普段どんな環境で開発、デバッグをすすめられているのか）
等、の内容が思いついました。

いかがでしょう。

**Comment by kou** [comment]
よさそうに思います！
最初はどれを選ぶのがよいでしょうねぇ。とっつきやすいやつを選ぶのがよいのかしら。

とっつきやすさとは。。。1回の開催で完結する規模、みたいな感じですかねぇ。

> ・コア機能のなにかの関連ソースを読んでみる。

は、範囲を調整すれば1回で完結する規模にはできそうな気がします。

> ・機能拡張のやり方(トークナイザの追加の話とか）の話。

は、1回だと厳しそうです。

> ・開発環境の話（開発者の方は普段どんな環境で開発、デバッグをすすめられているのか）

は、それだけだと時間が余っちゃいそうです。適宜紹介するみたいな方が向いている話題かもしれません。

↑はとっつきやすさでどれを選ぶのがよいか考えてみましたが、とっつきやすさ以外の観点もあると思います。

決め方はいろいろあるとは思いますが、まずは1つ話題を決めてやってみるのがいいのかも？と思いました！

**Comment by kou** [comment]
あ、 @shoutakenaka さんはどんな内容がいいなぁという希望はありますか？

**Comment by shogondo** [comment]
僕はコア機能に興味があるので、

> 範囲を調整すれば1回で完結する規模にはできそうな気がします

であれば、範囲を絞ってコア機能のソースを読む、というのがいいなぁと思います。

**Comment by shogondo** [comment]
ちなみに、弊社オフィスは外苑前駅のすぐ目の前の、NXB青山ビルの7Fです。
http://bbank.jp/overview

写真手前のラウンジスペースを使えます。

![会場](http://www.passion-navi.com/image/p10img/c_2576contact.jpg)

**Comment by naoa** [comment]
私はそのうちクエリをがちゃがちゃしたいのでmrubyでの拡張機能の書き方が知りたいです！（調べてないだけ）
まあ私の意見はあまり気にしなくてもいいです

**Comment by kou** [comment]
おぉ！とてもキレイなスペースですね！
机をとって椅子だけにしてしまうと各自ノートパソコンを開くのが大変になりそうなので、机は残したままがよさそうですね。

**Comment by kou** [comment]
> 僕はコア機能に興味があるので、
> 
> >  範囲を調整すれば1回で完結する規模にはできそうな気がします
> 
> であれば、範囲を絞ってコア機能のソースを読む、というのがいいなぁと思います。

この方向になるなら、どの機能にするかを考える必要がありますね。

ユーザーレベルの操作から紐付いている処理がイメージしやすくてよいかもしれません。たとえば、`select --match_columns COLUMN --query QUERY`したときにどう転置索引を使ってマッチさせているか、とか。動かせるとデバッガーで追いながらソースを読めるので理解も進みそうです。

**Comment by kou** [comment]
> 私はそのうちクエリをがちゃがちゃしたいのでmrubyでの拡張機能の書き方が知りたいです！（調べてないだけ）

これは、コアの機能というより、少し上のレイヤーの機能の話題になりそうですね。コアの機能→少し上のレイヤーの機能→コアの機能→…と順番にやるのも全体像が見えやすくなってよいのかもしれませんね。

**Comment by noranuk0** [comment]
> ユーザーレベルの操作から紐付いている処理がイメージしやすくてよいかもしれません。
> たとえば、select --match_columns COLUMN --query QUERYしたときにどう転置索引を使ってマッチさせているか、とか。動かせるとデバッガーで追いながらソースを読めるので理解も進みそうです。

なるほど、良い案と思います。
個人的には、インサート時に転置インデックスを作る部分とセットで見るのもよいかと思いましたが、１回の時間では厳しいですかね。

**Comment by kou** [comment]
> 個人的には、インサート時に転置インデックスを作る部分とセットで見るのもよいかと思いましたが、１回の時間では厳しいですかね。

そうですね。厳しそうな気がします。たぶん、最初はデバッガーがうまく動かない！とかあって手間取ったりすると思いますし。

ということで、1回目はまず「インサート時に転置インデックスを作る部分」をテーマにするのがよさそうに思いました。

これでよさそうなら↓に着手できそうです。
- イベントページ作成
- イベント開催日調整

どうでしょう？ > @noranuk0 @shoutakenaka

**Comment by shogondo** [comment]
+1 です。

**Comment by noranuk0** [comment]
内容については良いと思います。

ちょっと一点あるのですが、

対象とする方のスペックとか、参加される方ができれば事前に準備しておいてほしいもの
ってどんなものがあるでしょう？

例えば、groongaの内部に興味があって、C言語が普通に読める方とか　

用意しておいてほしいものとしては、環境については、たとえば
groonga 最新ソース一式とか。デバッグできる環境は事前にどの程度まで準備してほしいとか。

どうでしょう？

**Comment by kou** [comment]
> 内容については良いと思います。

では、内容は「インサート時に転置インデックスを作る部分」で決定としましょう！

> 対象とする方のスペックとか、参加される方ができれば事前に準備しておいてほしいもの
> ってどんなものがあるでしょう？
> 
> 例えば、groongaの内部に興味があって、C言語が普通に読める方とか　

難しいですねぇ。

まず、「groongaの内部に興味があって」は必須にしてよいと思います。興味がないと面白くないでしょうし。

「C言語が普通に読める」は「普通ってどのくらい？」問題があるので、「C言語でプログラムを書いたことがある人」または「書いたことはないけど他の言語ではプログラムを書いた経験はあって、C言語の文法は知っている人」くらいでどうでしょうか。

一回やってみて徐々に調整していくのが現実的なのかもしれません。

> 用意しておいてほしいものとしては、環境については、たとえば
> groonga 最新ソース一式とか。デバッグできる環境は事前にどの程度まで準備してほしいとか。

Debian GNU/Linuxで言えば↓相当のこと（typoあるかも）をやってあればすぐにソースコードを読んでいくところに入れそうな気はしますが、↓でつまづく人もいると思うので、最初はそこのサポートも必要なのかなぁと思っています。LinuxではなくOS X環境の人もいる場合は手順が変わりそうな気がします。たとえば、デバッガーはGDBではなく、LLDBを使わないといけない気がするので使い方が違いそうです。

``` text
% sudo apt-get install -V -y gdb autotools-dev zlib1g-dev ruby git build-essential pkg-config
% git clone --recursive https://github.com/groonga/groonga.git
% cd groonga
% ./autogen.sh
% ./configure --prefix=/tmp/local --enable-debug --with-ruby --enable-mruby
% make -j8 > /dev/null
% test/command/run-test.sh
```

こっちも、一回やってみて手順を確立できれば（ドキュメントにまとめるとか）次回以降は楽にできそうな気はします。

**Comment by noranuk0** [comment]
> 一回やってみて徐々に調整していくのが現実的なのかもしれません。
> 確かにそうですね。

もうちょっとゆるめに、全文検索エンジンの中身に興味があって・・・な方を対象に、groongaの実装を例に～
みたいな感じでもよいかと思いました。

> ebian GNU/Linuxで言えば↓相当のこと（typoあるかも）をやってあればすぐにソースコードを読んでいくところに入れそうな気はしますが、↓でつまづく人もいると思うので、
> ・・・・
> 　こっちも、一回やってみて手順を確立できれば（ドキュメントにまとめるとか）次回以降は楽にできそうな気はします。
> 確かにそうですね。
> テスト用のテーブル追加等も合わせて手順化してしまうのがよさそうと思います。

あと、windows + cmake + visual studio express な環境でも大丈夫でしょうか？
3.0.x の頃にこれでソースを追っかけてみたことはあるのですが、現行でも問題ないようでしたら
統合開発環境に慣れている方なら、こういうののほうがおそらくやりやすいかなと思いました。

**Comment by kou** [comment]
> もうちょっとゆるめに、全文検索エンジンの中身に興味があって・・・な方を対象に、groongaの実装を例に～
> みたいな感じでもよいかと思いました。

それでもよいと思います！

> あと、windows + cmake + visual studio express な環境でも大丈夫でしょうか？
> 3.0.x の頃にこれでソースを追っかけてみたことはあるのですが、現行でも問題ないようでしたら
> 統合開発環境に慣れている方なら、こういうののほうがおそらくやりやすいかなと思いました。

Visual Studio 2013以降であれば今でも大丈夫です！

AppVeyorというCIサービスでテストしているのでビルドできることは確認済みです。 https://ci.appveyor.com/project/groonga/groonga/history

**Comment by noranuk0** [comment]
> それでもよいと思います！

了解です！ではそんな感じにしてみましょう！

> Visual Studio 2013以降であれば今でも大丈夫です！

おお、gdbあまり詳しくないので、これは個人的にも非常に嬉しいです

では、事前準備というか、お持ちいただきたいものとして、
使い慣れたノートPCをご持参いただく感じでしょうか。

gdbの導入、デバッガの設定とかはフォロします。
guiな環境使いたい場合、windowsだとvisual studio express 2013 でも大丈夫です。
これはできれば事前にインストールしてきてほしいかもです（ちょっと時間掛かった気がするので）。

という感じでどうでしょう？

**Comment by kou** [comment]
> 了解です！ではそんな感じにしてみましょう！

そうしましょう！

> では、事前準備というか、お持ちいただきたいものとして、
> 使い慣れたノートPCをご持参いただく感じでしょうか。

そうですね。Doorkeeperでは参加者に質問することができる（使っているGroonga関連プロダクトは？というのがそれ）ので、環境を聞いておくとよい気がします！

> gdbの導入、デバッガの設定とかはフォロします。
> guiな環境使いたい場合、windowsだとvisual studio express 2013 でも大丈夫です。
> これはできれば事前にインストールしてきてほしいかもです（ちょっと時間掛かった気がするので）。
> 
> という感じでどうでしょう？

いいと思います！
Visual Studioはたしかにインストール済みのほうがよいですね！

https://www.visualstudio.com/ja-jp/downloads/download-visual-studio-vs を見るとVisual Studio Express 2013にもいろいろバージョンがあるみたいなんですが、デバッガーが付いているのはfor Windows Desktopですかねぇ。

このくらいの情報があるとイベントページを作成できそうでしょうか！？（ただし、開催日を除く）
（@noranuk0 さんも @shoutakenaka さんも https://groonga.doorkeeper.jp/ の管理者権限を付与してあります。）

イベントページは https://manage.doorkeeper.jp/groups/groonga/events/new から作成できます。 https://manage.doorkeeper.jp/groups/groonga/events から過去のイベントを辿れて過去のイベントページのソースも見れるので参考にしてください。

ということで、次は開催日を決めるのがよさそうでしょうか！？

**Comment by noranuk0** [comment]
> ということで、次は開催日を決めるのがよさそうでしょうか！？

そうですね。開催日と大まかなタイムテーブルな感じでしょうか。
時期的には告知かから開催まで３～４週間くらいなのかなー、
という感覚なのですが大体そんなもんでしょうか？

もうちょい早めたほうが、とか、間隔開けたほうが、とか有りましたらご教授ください。

**Comment by kou** [comment]
> 時期的には告知かから開催まで３～４週間くらいなのかなー、
> という感覚なのですが大体そんなもんでしょうか？
> 
> もうちょい早めたほうが、とか、間隔開けたほうが、とか有りましたらご教授ください。

そんなにたくさん人が集まる類のイベントではない（ただ話を聞くだけのイベントよりもだいぶ敷居が高そう）と思うので、今回は関係者（ここにコメントを書いている人たち）と会場の都合で決めていいんじゃないかと思います。興味のある人で都合があうなら参加してね、くらいのイメージです。

もしかしたら、日付を告知してみて「行きたかったけど都合が悪い」という声が聞こえたら再調整、でもいいかもしれません。

**Comment by noranuk0** [comment]
では、４月１３~１７日あたりで、会場の都合がつく日でいったん調整という形でどうでしょう？

ここご覧になられていて、参加を考えている方で、
この日なら、この日はちょっと・・・という日付があればコメントいただく感じで。

**Comment by shogondo** [comment]
会場の空きは、今のところこんな感じです。
- 4/7 (火)
- 4/9 (木)
- 4/13 (月)
- 4/20 (月)
- 4/23 (木)
- 4/24 (金)
- 4/27 (月)
- 4/30 (木)
- 5/1 (金)

**Comment by noranuk0** [comment]
@shoutakenaka さん、ありがとうございます！

では、一応１３日で仮決めということでよいでしょうか？

あと、建物の入退館時間も含めて、利用可能なお時間帯も教えていただけますか。

もし、ご都合つかない方が出てきて、会場がまだい空いていれば９日ｏｒ２０日も検討ということで。

**Comment by kou** [comment]
私は13日は大丈夫ですー

**Comment by noranuk0** [comment]
@shoutakenaka  さん

> あと、建物の入退館時間も含めて、利用可能なお時間帯も教えていただけますか。

↑と合わせて、もう一点ご確認事項です。
以前、机をどかした状態で３０人程度とお伺いしましたが、机を残した状態では何人くらい入るでしょうか？

**Comment by shogondo** [comment]
@noranuk0 さん

> 建物の入退館時間も含めて、利用可能なお時間帯も教えていただけますか。

19時から23時まで使えます。

> 机を残した状態では何人くらい入るでしょうか？

20人くらいです。
以前添付した写真に写っている白いテーブルが７つあります。あのテーブルが２人でPCをおいて作業ができるくらいのサイズです。
その他にテーブル代わりに使っているビリヤード台が１つあって、これが６人くらいいけます。

**Comment by noranuk0** [comment]
@shoutakenaka さん　ありがとうございます。

では、
募集定員２０人　

時間は
受付　１９：００～
開始　19：３０～２１：００　ｏｒ　２１：３０頃まで
※　ソースの展開とか、デバッグ環境の準備などは、来た人から順次フォローしていく。

で、とりあえずイベントページ作成＆告知な流れでいいでしょうか。

**Comment by noranuk0** [comment]
後、当日は、どんな感じで進めてくのがいいでしょう。

この辺は、実際開発されている方々のご意見を伺いたいです。

**Comment by kou** [comment]
> 後、当日は、どんな感じで進めてくのがいいでしょう。

こんな感じでどうでしょうか！？
- 手元でビルドできる状態にする
- ビルドしたGroongaで転置インデックスを作るGroongaコマンド（これは事前に準備したほうがよさそう）を実行できることを確認
- デバッガーまたはコードを読んで「インサート時に転置インデックスを作る部分」を探す
- 「インサート時に転置インデックスを作る部分」にブレークポイントを張る
- コードを読んでこうなってそうと予想を立てる→実際にステップ実行で予想が正しいかを確認を繰り返す
- 「インサート時に転置インデックスを作る部分」を理解できる！

**Comment by shogondo** [comment]
@noranuk0 さん

時間調整できました。
受付 18時半〜
開始 19時〜
でも大丈夫です。

**Comment by naoa** [comment]
デバッグ環境準備する場合は、最適化オプション抜いてビルドできるようにしたほうがよさそうですね。ないとビルドだけで３０分ぐらいかかりそうです。

http://qiita.com/groonga/items/24ea9b51537217b9f526

**Comment by noranuk0** [comment]
@naoa さん

確かにそうですね。ステップ実行とか変数ウォッチがうまくできなくなる可能性が、的な弊害も出てきますし。

@shoutakenaka さん 
すみません、１８：３０受付開始だとちょっとぎりぎりかもです(僕が・・）
なので、１８：４５分受付開始　１９：１５ごろから開始　という形で イベントページ作りますー

**Comment by noranuk0** [comment]
イベントページを作成しました。

内容のご確認のうえ、追記、訂正等ありましたらお願いいたします。

@shoutakenaka さん
受け付け方法、会場での注意事項(飲食、インターネット接続環境、電源など？）ありましたら追記をお願いいたします。

 https://groonga.doorkeeper.jp/

**Comment by kou** [comment]
あ、イベントページのURLはだしちゃっていいですよ。告知しなければどうせ気付かれないので。

ログインしていると↓の上の方に「イベント編集」というボタンがあるので、そこから内容を編集できます。
https://groonga.doorkeeper.jp/events/23042

**Comment by shogondo** [comment]
@noranuk0 さん

イベントページに入館と会場の設備について追記しました。

**Comment by noranuk0** [comment]
@shoutakenaka さん

ありがとうございます！

他、特に何もなければ、公開したいと思いますがいかがでしょう。

後で、記載漏れ追記などありましたら適宜修正ということで。

**Comment by kou** [comment]
いいと思います！

**Comment by noranuk0** [comment]
公開しました！

**Comment by kou** [comment]
ありがとうございます！
地図の下の説明文のどこかにも受付時間・開始時間を書いた方がいいかもしれないと思いました！ページの上の方に書いているのですが、薄めの字なので見逃しそうだと思いまして。。。

**Comment by kou** [comment]
groonga.org で告知しました！
http://groonga.org/ja/blog/2015/04/01/groonga-source-code-read-announce.html

（TwitterとFacebookにも流しました。）

groonga.orgのソースは https://github.com/groonga/groonga.org/ にあって、ブログの記事を公開したいときは  https://github.com/groonga/groonga.org/commit/da2f5326df9103b74d1ff1bee752334209be45fe のようにすればよいので、groonga.orgに告知やレポートなどをあげる場合はpull requestを送ってくれれば取り込みます！活用してやってください。

**Comment by noranuk0** [comment]
@kou さん
ありがとうございます！人、あつまるかなー

> 地図の下の説明文のどこかにも受付時間・開始時間を書いた方がいいかもしれないと思いました！
> ページの上の方に書いているのですが、薄めの字なので見逃しそうだと思いまして。。。

なるほど、確かにそうですね。後程加筆しておきます。

**Comment by kou** [comment]
@shoutakenaka 会場にホワイトボードってあったりしますか！？なかったら紙とペンを持っていったほうが図で書いて理解しやすくなるかなぁと思いまして。

**Comment by shogondo** [comment]
@kou ホワイトボード使えます！

**Comment by kou** [comment]
さすがです！！！

**Comment by kou** [comment]
事前準備はなにがありますかねぇ。こんな感じでしょうか。
- [ ] 転置インデックスを作るGroongaコマンド
- [x] Windows環境でGroongaをビルドできることを確認（当日でもよい？。事前にやるなら手順メモを残したほうがいいかも）
- [x] 対象Groongaのバージョンを決める（masterにする？リリースしたtar.gz/zipを使う？）

Groongaコマンドなど共有する必要があるファイルはこのリポジトリーにpushしていっていいです！

**Comment by noranuk0** [comment]
@kou さん

> 転置インデックスを作るGroongaコマンド

公式サイトのチュートリアルに載っているテーブル作成＆データインサート用のgroongaコマンドで大丈夫かなと思いましたがいかがでしょう。

> Windows環境でGroongaをビルドできることを確認（当日でもよい？。事前にやるなら手順メモを残したほうがいいかも）

今、cmake + visual studio 2013 express で動作確認をやろうとしていたところです、結果は追って記載いたします。

> 対象Groongaのバージョンを決める（masterにする？リリースしたtar.gz/zipを使う？）

特に理由はないですが、最新リリース版(5.0.2)で合わせたほうがいいかなと思いました。

**Comment by noranuk0** [comment]
> 今、cmake + visual studio 2013 express で動作確認をやろうとしていたところです、結果は追って記載いたします。

visual studio 2013 express Desktop で、ビルドｏｋ　＆　統合開発環境内でのデバッグちゃんとできてます。
環境作成手順とか、余裕があればまとめておきます。

**Comment by kou** [comment]
> 公式サイトのチュートリアルに載っているテーブル作成＆データインサート用のgroongaコマンドで大丈夫かなと思いましたがいかがでしょう。
- http://groonga.org/ja/docs/tutorial/introduction.html#create-a-table
- http://groonga.org/ja/docs/tutorial/introduction.html#create-a-column
- http://groonga.org/ja/docs/tutorial/introduction.html#load-records
- http://groonga.org/ja/docs/tutorial/introduction.html#create-a-lexicon-table-for-full-text-search

↑のGroongaコマンドということですね。よいと思います。

レコード数が9個ありますが、単純にするために1個に減らしてもいいかもしれません。

> 特に理由はないですが、最新リリース版(5.0.2)で合わせたほうがいいかなと思いました。

では、5.0.2で統一しましょう！

**Comment by kou** [comment]
> visual studio 2013 express Desktop で、ビルドｏｋ　＆　統合開発環境内でのデバッグちゃんとできてます。

おぉ！よかったです！

> 環境作成手順とか、余裕があればまとめておきます。

ありがとうございます！

**Comment by noranuk0** [comment]
イベントページに、当日参照するソースコードのバージョンについての説明を書き忘れていたので追記しておきました。

**Comment by kou** [comment]
ありがとうございます！

参加者、結構いますね！

**Comment by noranuk0** [comment]
> 参加者、結構いますね！

そうですね。ここに書き込んでいるメンバーのぞいて５、６人かなー、と勝手に思っていたので、結構びっくりしています。

あと、今使っているプロダクトのアンケートで、まだ使っていない　と回答されている方も結構いらっしゃったのも意外でした。

**Comment by kou** [comment]
> あと、今使っているプロダクトのアンケートで、まだ使っていない　と回答されている方も結構いらっしゃったのも意外でした。

もしかしたら、外から（ユーザーから）見えるGroongaの動きも説明しないといけないのかもしれませんね。どこまでフォローするのがよいか難しそうですよねぇ。あまり進まなくてもよい、と割りきっちゃうのがいいんですかねぇ。

**Comment by noranuk0** [comment]
> もしかしたら、外から（ユーザーから）見えるGroongaの動きも説明しないといけないのかもしれませんね。どこまでフォローするのがよいか難しそうですよねぇ。あまり進まなくてもよい、と割りきっちゃうのがいいんですかねぇ。

うーん、それをやってしまうと、groongaの内部ロジックを見てみたいと思ってきたコアな方が退屈してしまうような気がします。
例えば、ウィキペディアの「転置インデックス」のページ等を参照しつつ、転置インデックスとは的な説明を簡単に入れた後、groongaでの転置インデックス作成の実装方法の話に持っていく形とかではどうでしょう。

そういえば、もう明日なんですね。

**Comment by kou** [comment]
> うーん、それをやってしまうと、groongaの内部ロジックを見てみたいと思ってきたコアな方が退屈してしまうような気がします。
> 例えば、ウィキペディアの「転置インデックス」のページ等を参照しつつ、転置インデックスとは的な説明を簡単に入れた後、groongaでの転置インデックス作成の実装方法の話に持っていく形とかではどうでしょう。

「（興味はあるけど）基礎知識はぜんぜんない人」より「基礎知識がある人」を優先ってことですね。「決め」の問題だと思うので、最初に宣言すればそれでアリだと思います！
Doorkeeperでは参加者にメッセージを送ることができるので、事前に「こういう方針だよー」とか「基礎知識がない人はここを読んでおくと得るものが多くなると思うよー」みたいなことを伝えておくのもありかもしれませんね。直前なのでさすがに読んでいる時間はないかもしれませんが。。。

**Comment by kou** [comment]
@shoutakenaka 18:30くらいに着くように向かいます！会場準備、少しお手伝いできると思います！今日はよろしくお願いします！

**Comment by shogondo** [comment]
@kou こちらこそよろしくお願いします！

**Comment by noranuk0** [comment]
私もそれくらいの時間に着くように向かいます（もう少し遅くなるかも）。

一応、Visual Studio 2013 express for windows desktop のインストールイメージの入ったUSBメモリー１本持っていきます。

**Comment by shogondo** [comment]
自分用にUbuntuのVagrant Boxを作ったのですが、せっかく作ったので共有します。
[ここ](https://github.com/shoutakenaka/workshop-groonga-code-reading)にVagrantfileがあります。
- Ubuntu Server 14.04.2
- 最低限のパッケージをインストールしてGroonga 5.0.2を[ビルド](https://github.com/shoutakenaka/workshop-groonga-code-reading/blob/master/setup.md)した状態

Box単体でダウンロードする場合は[こちら](https://www.dropbox.com/s/jkskzrylt54brwh/groonga-5.0.2.box?dl=0)から。

**Comment by kou** [comment]
おぉ！

`./configure`のオプションは`--enable-debug`の方がおすすめです！`--enable-debug`をつけると中で勝手に`CFLAGS`と`CXXFLAGS`を設定するんです。なので、挙動は同じなんですが、後でみたときにわかりやすいので`--enable-debug`の方がおすすめなのです。

**Comment by shogondo** [comment]
@kou なるほど、勉強になりました。ありがとうございます！

**Comment by kou** [comment]
すみません…
近くまで来ている気はするんですが迷っています…

**Comment by shogondo** [comment]
外苑前駅1a出口出てすぐ左です

**Comment by shogondo** [comment]
みずほ銀行の左隣のビルです

**Comment by noranuk0** [comment]
すみません。でるのが遅くなってしまったので到着19時過ぎになりそうです

**Comment by shogondo** [comment]
```
table_create --name Site --flags TABLE_HASH_KEY --key_type ShortText

select --table Site

column_create --table Site --name title --type ShortText

select --table Site

load --table Site
[
{"_key":"http://example.org/","title":"This is test record 1!"},
{"_key":"http://example.net/","title":"test record 2."},
{"_key":"http://example.com/","title":"test test record three."},
{"_key":"http://example.net/afr","title":"test record four."},
{"_key":"http://example.org/aba","title":"test test test record five."},
{"_key":"http://example.com/rab","title":"test test test test record six."},
{"_key":"http://example.net/atv","title":"test test test record seven."},
{"_key":"http://example.org/gat","title":"test test record eight."},
{"_key":"http://example.com/vdw","title":"test test record nine."},
]

select --table Site

table_create --name Terms --flags TABLE_PAT_KEY|KEY_NORMALIZE --key_type ShortText --default_tokenizer TokenBigram

column_create --table Terms --name blog_title --flags COLUMN_INDEX|WITH_POSITION --type Site --source title
```

**Comment by kou** [comment]
``` text
table_create --name Site --flags TABLE_HASH_KEY --key_type ShortText
column_create --table Site --name title --type ShortText
table_create --name Terms --flags TABLE_PAT_KEY|KEY_NORMALIZE --key_type ShortText --default_tokenizer TokenBigram
column_create --table Terms --name blog_title --flags COLUMN_INDEX|WITH_POSITION --type Site --source title
```

**Comment by kou** [comment]
``` text
truncate Site
load --table Site
[
{"_key":"http://example.org/","title":"This is test record 1!"},
]
```

**Comment by kou** [comment]
/tmp/test.grn:

``` text
table_create --name Site --flags TABLE_HASH_KEY --key_type ShortText
column_create --table Site --name title --type ShortText
table_create --name Terms --flags TABLE_PAT_KEY|KEY_NORMALIZE --key_type ShortText --default_tokenizer TokenBigram
column_create --table Terms --name blog_title --flags COLUMN_INDEX|WITH_POSITION --type Site --source title

load --table Site
[
{"_key":"http://example.org/","title":"This is test record 1!"},
]
```

command line:

``` text
% rm -rf /tmp/db && mkdir -p /tmp/db && gdb --args /tmp/local/bin/groonga --file /tmp/test.grn -n /tmp/db/db
```

**Comment by kou** [comment]
`~/.gdbinit`

``` text
set history save
set history size 10000
set history filename ~/.gdb_history
set breakpoint pending on
set print pretty on
set print static-members off
set charset UTF-8
```

**Comment by redfigure** [comment]
手伝います！

**Comment by kou** [comment]
ほんとにイベントを開催できました！イベント主催・会場提供、ありがとうございました！

次回開催に向けた話は #6 で！

**Comment by noranuk0** [comment]
昨日はお疲れ様でした＆私の思いつきを実現していただきありがとうございました。

全く別件で恐縮ですが、
当日、Windowsのデバッグ環境構築の手伝いをしていて気づいたのですが、
groonga 公式サイトの Windows -　ソースからビルド　のページに誤植が有りました。

誤) cmake . -G "Visual Studio 10 Win64" -DCMAKE_INSTALL_PREFIX=C:\groonga
正) cmake . -G "Visual Studio 12 Win64" -DCMAKE_INSTALL_PREFIX=C:\groonga

誤) Visual Studio 2010
正) Visual Studio 2013

かと思います。

**Comment by kou** [comment]
ありがとうございます！ソースの方は更新しておきました！サイトの方は次のリリースのときに反映されます。
