### ISSUE TITLE
Groongaドキュメント読書会7

### ISSUE THREAD

**Issue by redfigure** [groonga/meetup#7]
準備中です。

Todo:
- [x] [groonga-document-read-ja](https://github.com/groonga/groonga-document-read-ja)を[meetup](https://github.com/groonga/meetup/)へ統合
- [x] DDLとJSONを準備
- [x] 日程調整
- [x] 会場確保
- [x] イベントページ作成
- [x] 告知
- [x] 中止告知（台風のため）
- [x] スケジュール再設定
- [x] 開催再告知

**Comment by redfigure** [comment]
@kou 日程なんですが5/12（火）はどうでしょうか？

**Comment by kou** [comment]
私は大丈夫です！

**Comment by tamano** [comment]
自分も5/12なら参加出来そうです。

**Comment by redfigure** [comment]
一旦5/12で会議室抑えます。

**Comment by kou** [comment]
あ、イベントページの作成、まだでしたね。

**Comment by kou** [comment]
@tamano さんもDoorkeeperの管理者に加えておきました！

**Comment by tamano** [comment]
@kou さん、ありがとうございます。

次回の再開位置について。
本来であれば、[4.8. パトリシア木による前方一致検索](http://groonga.org/ja/docs/tutorial/patricia_trie.html)からかと思いますが、前回かなり混沌とした状態でタイムアップになってしまったので、もう一度、前回の最後にやった[4.7.3. カラムインデックスによる関連テーブルをまたぐ検索](http://groonga.org/ja/docs/tutorial/match_columns.html#nested-index-search-among-related-table-by-column-index)を読み直すところから再開してはと思うのですが、どうですか？

**Comment by kou** [comment]
さすがです！
いいと思います！

**Comment by tamano** [comment]
@redfigure さん、イベントページ作ってみました！
会場の注意事項、前回のをそのままコピペしてるんですが問題ないか見てもらっていいですか？
OKであれば、そのまま公開してもらえると嬉しいです。

https://groonga.doorkeeper.jp/events/24629

**Comment by redfigure** [comment]
@tamano さん、ありがとうございます。確認して公開状態にしました。

**Comment by kou** [comment]
日付が5/12（火）じゃなくて5/11（月）になってしまっているみたいです！

**Comment by tamano** [comment]
@redfigure さん、ありがとうございます。

@kou さん、ご指摘ありがとうございます！ 失礼しました。直しました。

**Comment by redfigure** [comment]
@tamano @kou 気づきませんでしたありがとうございます。

告知Done.

**Comment by tamano** [comment]
:tada:

**Comment by redfigure** [comment]
受付と正面入口が閉まる時間帯について諸注意の項目を追加しました。
https://groonga.doorkeeper.jp/events/24629

DDLとJSONって今あるやつで大丈夫なんでしたっけ？
復習がてら手を動かしたほうがいいかしら。

**Comment by redfigure** [comment]
@kou @tamano
先日MLで上がった下記、読書会で非常に強力なツールになりそうではないかと思うのですが採用してみませんか？

https://github.com/hiroyuki-sato/groonga_practice

**Comment by kou** [comment]
いいと思います！
メーリングリストでも返事をするのはどうでしょうか！

**Comment by redfigure** [comment]
Done.

時間を見つけて挙動確認しよう。

**Comment by tamano** [comment]
ありがとうございます :+1:

**Comment by redfigure** [comment]
@kou @tamano 
明日台風直撃のようですが、どうしましょうか。。。
ちょうど移動時間に東京直撃っぽいので中止のほうがいいかと考えています。

**Comment by kou** [comment]
おぉ。。。中止にしましょうか。。。と思ったんですが、最新情報（？） http://www.tenki.jp/forecaster/diary/maki_horie/2015/05/11/24111.html だと東京あたりにくるのは13日3時くらいになったみたいなので大丈夫そうです！

**Comment by redfigure** [comment]
むむむ
http://www.jma.go.jp/jp/typh/1506.html
http://weathernews.jp/typhoon/

まだ台風情報に結構なずれがありますね。
明日の速報を見て決めましょうか。
東京上空通過が3時だとしても暴風や豪雨で電車が止まる可能性もありますし、他社からいろんな人が来るので安全マージンはとっておきたいです。

**Comment by redfigure** [comment]
@kou @tamano 
最新情報を確認したところ21時から0時にかけて台風6号は神奈川から東京近辺に差し掛かるものと思われます。
その頃から温帯低気圧に変わり始めるとのことですが、ちょうど勉強会が終わる時間帯にぶつかります。

安全に帰ることを保証できない以上、中止に1票と考えます。

**Comment by tamano** [comment]
@redfigure
個人的には参加される方の自己判断でいいんじゃないかなぁと考えていましたが、会場提供頂いている @redfigure さんの判断でいいと思います。

**Comment by redfigure** [comment]
正直なところ会場から動けなくなって帰宅困難になった際の責任をウチが負うのか、という点でかなり不安があります。

**Comment by tamano** [comment]
はい。そういう意味で、 @redfigure さんの判断は尊重されるべきだと思うので、自分も中止でいいと考えています。

**Comment by kou** [comment]
では中止にしましょう！

**Comment by redfigure** [comment]
@kou @tamano 
お手数をお掛けします。
昼に中止の告知をDoorkeeperから送信します。

リスケして再度開催したいと思いますので、6月1週目、2週目あたりで候補日を教えていただけますか？’

**Comment by kou** [comment]
> 昼に中止の告知をDoorkeeperから送信します。

ありがとうございます！

> リスケして再度開催したいと思いますので、6月1週目、2週目あたりで候補日を教えていただけますか？

私は6/1（月）と6/8（月）以外なら大丈夫です！

**Comment by tamano** [comment]
@redfigure
お手数ですがよろしくお願いします。
自分は6月はいつでも大丈夫です。

**Comment by myokoym** [comment]
@redfigure 中止の告知が届いていない気がするのですが、私だけでしょうか？

**Comment by redfigure** [comment]
@myokoym doorkeeper からは12:09にメッセージを送信したことになっているのですが、確かに飛んでませんね。。。
ちょっと状況確認します。

**Comment by redfigure** [comment]
Doorkeeperの使い方を間違ってました。
今度こそちゃんと通知が届いたと思います。

**Comment by myokoym** [comment]
通知届きました、ありがとうございます！
Twitterでもつぶやいておきました。
https://twitter.com/groonga/status/597996127900676096

**Comment by redfigure** [comment]
@myokoym ありがとうございます！

**Comment by redfigure** [comment]
@kou @tamano 
6/4（木）で会議室抑えました！
日曜辺りにイベントページ作り直します。

**Comment by kou** [comment]
ありがとうございます！
後で見たときにわかりやすいように今のイベントページのタイトルに「（台風のため中止）」と入れておきました。

**Comment by tamano** [comment]
@kou @redfigure
ありがとうございます！

**Comment by redfigure** [comment]
@kou 月曜の昼休み時間帯あたりに再度doorkeeperから通知を出そうと思います。
合わせてTwitterのGroonga公式アカウントからイベントページの告知をお願いできますか？

**Comment by kou** [comment]
はい！もちろんです！

**Comment by kou** [comment]
この間、[Groonga新リリース自慢会 5.0.4](https://groonga.doorkeeper.jp/events/25515)に参加した人から、「参加したいけどすでに7回目まで行っていて、今から参加すると邪魔になりそうで参加に踏み切れない。。。」という意見をもらいました。

その場では「むしろ途中参加して欲しい。途中参加して、わからないところをわからないと聞いて欲しい。そうしたら、既存の参加者が説明する機会ができて、既存の参加者の理解が進んだり、理解していないところがわかってうれしい。」ということを説明しましたが、たしかに、回を重ねたことで途中から参加するハードルがあるのもわかる気がします。

ということで、↑みたいな途中参加ウェルカムだよ！みたいなことをイベントページに明記しておくといいかなぁと思いました。どうですかねぇ。

**Comment by redfigure** [comment]
@kou 
次回から書きます。

とはいえ書き方を工夫する必要はあると思っています。
内輪感のない感じが出せればいいのかなとも思うのですが、実際に文言を考えるとき相談させてください。

**Comment by kou** [comment]
> 内輪感のない感じが出せればいいのかなとも思うのですが、実際に文言を考えるとき相談させてください。

はい！

**Comment by redfigure** [comment]
Groonga Practice
https://github.com/hiroyuki-sato/groonga_practice

**Comment by redfigure** [comment]
今回の課題点的なリスト
- 立ち上がりの情報展開やDDLの可視化などをうまくやるといいかも
- 最低限の手順について情報共有ができるといいかも
  - 少なくともtry-groongaもしくは手元のマシンで、groongaを立ちあげられる状態までのメモが欲しい。
- クイックスタートがあるととっかかりやすいかも
- ドキュメントの構築をもっと手軽にできないか
- テーブル作成時の経過を見れたらわかりやすいのではないか（パラパラマンガやストップモーション的な感じ）
- サンプルコードの実行結果を、ホワイトボードに1行ずつ書き出しながら進めるとわかりやすいのでは
  - 基礎的な部分も含めてやると復習にもなるかも。

@tamano さんの改善とかを聞き漏らしたので追加があればおねがいします。

次回同じく4.7.3前のものと似たサンプルのスキーマ定義です。から

**Comment by tamano** [comment]
追記させてもらいました！
