### ISSUE TITLE
Groongaドキュメント読書会8

### ISSUE THREAD

**Issue by redfigure** [groonga/meetup#9]
そろそろ次を考えます。
13日の週か20日の週あたりに実施したいのですが @kou さんのご予定はいかがでしょうか？

Todo：
- [x] 日程調整
- [x] 会場確保
- [x] イベントページ作成（新規参加者向けに文言改定予定）
- [x] 告知

前回課題：
- 立ち上がりの情報展開やDDLの可視化などをうまくやるといいかも
- 最低限の手順について情報共有ができるといいかも
  - 少なくともtry-groongaもしくは手元のマシンで、groongaを立ちあげられる状態までのメモが欲しい。
- クイックスタートがあるととっかかりやすいかも
- ドキュメントの構築をもっと手軽にできないか
- テーブル作成時の経過を見れたらわかりやすいのではないか（パラパラマンガやストップモーション的な感じ）
- サンプルコードの実行結果を、ホワイトボードに1行ずつ書き出しながら進めるとわかりやすいのでは
  - 基礎的な部分も含めてやると復習にもなるかも。

以上から、導入資料（イベントで使えるクイックスタートな手順）があると良いかもしれない。
そこでブラッシュアップして公式ドキュメントに取り込む流れが作れたらなお良い。

撮影は積極的にやりたい。
が、コストが重いと撮影者の集中力に影響が出るのでそれは避けたい。
手軽なスマホアプリなどがあれば共有いただきたいです（こっちでも探してみます）。
撮影された写真はGoogle DriveとかRabbit（こっちは参加レポートとして）などで共有すると良いかも。

初心者や初参加者がまるでわからん！と火傷せずに学べるイベントを目指したいですね。。。

**Comment by kou** [comment]
> 13日の週か20日の週あたりに実施したいのですが @kou さんのご予定はいかがでしょうか？

13日の週は↓が大丈夫です！
- 7/14（火）
- 7/15（水）
- 7/17（金）

20日の週は7/20（月、海の日）以外大丈夫です！

> 撮影は積極的にやりたい。
> が、コストが重いと撮影者の集中力に影響が出るのでそれは避けたい。
> 手軽なスマホアプリなどがあれば共有いただきたいです（こっちでも探してみます）。

Androidで調べてみたらこんなのがありました。
- GIF Camera: http://octoba.net/archives/20140620-android-app-gif-camera-326576.html
- GifBoom: http://appllio.com/android-tool-app/20120216-1625-gifboom-animation-camera
- GIFモブ: https://play.google.com/store/apps/details?id=com.photo3dapps.gifmob.free&hl=ja
  - サンプル: http://photo3d-apps.blogspot.jp/2013/10/gif-mob-gif-camera-sample-images.html

> 初心者や初参加者がまるでわからん！と火傷せずに学べるイベントを目指したいですね。。。

すばらしいです！そうしたいです！

**Comment by redfigure** [comment]
@kou 
7/22（水）で会議室を抑えました。

アプリはどれも似たり寄ったりな印象ですねえ。
むしろスマホを固定する **脚** の方が重要に思えてきました。

こういうのの組み合わせでいけるか、セリアとかで適当なもの組み合わせてDIYするか・・・。
http://www.amazon.co.jp/dp/B00GGGLL1E/
http://www.amazon.co.jp/dp/B004WM07PA/
http://www.amazon.co.jp/dp/B0038YWLCA/

撮影機材選びのようになってきたなあｗ

**Comment by redfigure** [comment]
@kou @tamano 

https://groonga.doorkeeper.jp/events/28322

イベントページを作成しました。
後半の文言を初心者が参加しやすいように、中級者以上がサポートしやすいようにということを意識して大幅に変更してみました。

昼ごろ通知付きで公開しようと思います。

**Comment by kou** [comment]
とてもよくなったと思います！

**Comment by redfigure** [comment]
ありがとうございます！
イベントページを公開し、通知を出しました。

クイックスタート的な資料（スライドかmarkdown）はこの週末で作ってみようと思います。
ドキュメントコントリビュート専用の手順（OSXのは @tamano さんのがある）も余力があれば・・・。

**Comment by tamano** [comment]
いい案内文ですね。ありがとうございます！
(自分は今回はちょっと参加できないのですが :sob:  すみません)

ドキュメント更新の手順ですが、CentOSについては[Groonga・Mroongaのドキュメントを更新する方法](http://createfield.com/Groonga%E3%83%BBMroonga%E3%81%AE%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E3%82%92%E6%9B%B4%E6%96%B0%E3%81%99%E3%82%8B%E6%96%B9%E6%B3%95)でいけそうなので、作るとしたらUbuntuとWindowsですかね。

**Comment by redfigure** [comment]
Nice Share!
公式の手順がDebian（Ubuntuでもほぼ一緒？）なのでWindowsは必要かもですねえ。

**Comment by redfigure** [comment]
あと撮影用の脚、買いました。
http://www.amazon.co.jp/dp/B00GGGLL1E/

**Comment by tamano** [comment]
あ、なんかカッコいい！

**Comment by kou** [comment]
> イベントページを公開し、通知を出しました。

ありがとうございます！

> クイックスタート的な資料（スライドかmarkdown）はこの週末で作ってみようと思います。

おぉ！！！

Windowsでの更新手順は難しそうですねぇ。ローカルでの動作確認はしなくていいので、GitHubのエディター機能で直接書き換えてpull requestしてね、でいいのかもしれないですね。

撮影準備はバッチリですね！

**Comment by redfigure** [comment]
> Windowsでの更新手順は難しそうですねぇ。

cygwinや[babun](http://babun.github.io/)を使えばあるいは、とも思ったのですがその環境でCP932って何もしなくても大丈夫だっけ、とかmake.bat作んなきゃいけないな（autogen.shとかで生成されませんでしたよね？）とか色々考える/対応することが多そうです。

> GitHubのエディター機能で直接書き換えてpull requestしてね

いいアイディアだと思います！

**Comment by tamano** [comment]
「ドキュメント更新するためには、まずCygwin入れてね！」って相当ハードル高いですよね笑
僕もGitHubで直接修正に一票です。

**Comment by redfigure** [comment]
@kou 

クイックスタート資料を作ってみました（といっても公式ドキュメントまんまですが）。
http://redfigure.github.io/slide/groonga_quickstart/#/

とはいえ参加者が我々以外おらず、これは中止かなという雰囲気が・・・。

**Comment by kou** [comment]
ありがとうございます！手短にまとまっていてよいと思います！

@redfigure さんの理解が進むだけでもやる意味はあるのでやりましょう！
（会場のぐるなびさんの人たちに声をかけるともう少し集まったりしないかしら。。。）

**Comment by redfigure** [comment]
@kou 
やりましょう。

一応うちの人間にも声かけてみます。

**Comment by myokoym** [comment]
いつも参加レポートを書いてくださっている @tamano さんがいなかったので、代打で書きました。

Groongaドキュメント読書会8 参加レポート - Qiita : http://qiita.com/myokoym/items/e624e11d599cfa46bc87

**Comment by redfigure** [comment]
@myokoym ありがとうございます！
土日でこちらもレポート作成します。
